# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
