# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170307_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
